Roman
sodabarauf/numerial-roman pull request #1
Opened 2024-06-25 17:46 UTC by sodabarauf

this is second project of javascript Roman Numeral Converter, here i did these things:
-followed GITHUB workflow.
-added linters.
-added descriptive README.md file
-deploy the link.
-added index.html, style.css, javascript.js file.
-added html tags like p, div, input, button.
-added some styles and properties to style.css file.
-added some concept of javascript.
-created asset folder for images.

2024-06-28 09:41 UTC, humuyar commented
hi@sodabarauf
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!
bravo🥳
Status Approved 👍 Great Design Implemented
✔ Created a professional Repo (You created a repository with your project name)
✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔ Commit messages are meaningful
✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔ No linter errors (All linters checks have been passed 🟢)
✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔Your code is clean
✔Your repo has a professional README.md file

2024-06-28 09:50 UTC, sodabarauf commented
> hi@sodabarauf Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!! bravo🥳 Status Approved 👍 Great Design Implemented ✔ Created a professional Repo (You created a repository with your project name) ✔ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch) ✔ Commit messages are meaningful ✔ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code) ✔ No linter errors (All linters checks have been passed 🟢) ✔ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review) ✔ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request) ✔Your code is clean ✔Your repo has a professional README.md file

@humuyar 
dear humaira, tnx from your feedback.

2024-06-28 22:23 UTC, ahzamir requested changes
### Hi @sodabarauf 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/sodabarauf/numerial-roman/assets/96838030/0d3b1bc1-7748-4420-9022-648cbd9860c1)


# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
❌Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-28 22:23 UTC, ahzamir commented on styles.css
- Although your design is impressive but it is not responsive make it responsive and request for a re-review.

2024-06-29 06:34 UTC, sodabarauf commented on styles.css
> * Although your design is impressive but it is not responsive make it responsive and request for a re-review.

@ahzamir,
sir thanks from you, i make it responsive please re-review this design.

2024-06-29 06:36 UTC, sodabarauf commented
@ahzamir 
sir, thanks from you, i make page responsive you can re-review this design.

2024-06-29 18:30 UTC, ahzamir requested changes
@sodabarauf 

- Still your design is not responsive, please does not submit your project with the same mistake and issue before checking it.

![image](https://github.com/sodabarauf/numerial-roman/assets/96838030/49bc0542-8754-42fa-85d1-1cf20b69501f)

2024-06-29 21:21 UTC, sodabarauf commented
@ahzamir 
sir, i make it responsive form mobile versions, please re-review.
thank you.

2024-07-01 06:53 UTC, ahzamir approved these changes
### Hi @sodabarauf 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/sodabarauf/numerial-roman/assets/96838030/b8ddcbb6-79c6-4e39-8820-19203d2f57d4)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-01 09:42 UTC, sodabarauf commented
@ahzamir 
thank you much more, sir.

2024-07-01 09:42 UTC, merged